# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wf6taKBu7n-OV-inYc5MmEpM2xTmV3sH
"""

import os

# Detect environment
IS_COLAB = 'google.colab' in str(get_ipython())

if IS_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')
    # Use your existing Google Drive structure
    DIRECTORY_PATH = '/content/drive/MyDrive/EntireDataset'
    OUTPUT_PATH = '/content/drive/MyDrive/ExtractedText'
else:
    # Standard local paths for GitHub users
    DIRECTORY_PATH = './data/raw_pdfs'
    OUTPUT_PATH = './data/extracted_json'

os.makedirs(OUTPUT_PATH, exist_ok=True)

"""# Mount"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

"""# Libraries"""

!pip install transformers torch pdfplumber sklearn

!pip install pdfplumber

import pdfplumber

"""# Extraction"""

import os
import pdfplumber
import json

# Define the directory containing PDFs
directory_path = '/content/drive/MyDrive/EntireDataset'

# Function to extract text from a single PDF
def extract_pdf_text(pdf_path):
    try:
        with pdfplumber.open(pdf_path) as pdf:
            text = ''
            for page in pdf.pages:
                text += page.extract_text() or ''  # Handle pages with no text
            return text
    except Exception as e:
        print(f"Error processing file {pdf_path}: {e}")
        return None

# Directory to save the extracted JSON data
output_path = '/content/drive/MyDrive/ExtractedText'
os.makedirs(output_path, exist_ok=True)  # Create directory if it doesn't exist

# Dictionary to store extracted text
extracted_texts = {}

processed_files = 0

for file_name in os.listdir(directory_path):
    if file_name.endswith('.pdf'):  # Ensure it's a PDF
        file_path = os.path.join(directory_path, file_name)
        print(f"Processing: {file_name}")

        # Extract text
        pdf_text = extract_pdf_text(file_path)
        if pdf_text:
            extracted_texts[file_name] = pdf_text  # Store extracted text in dictionary

        processed_files += 1
        if processed_files % 100 == 0:
            print(f"Processed {processed_files} files...")

# Save the extracted texts to a JSON file
output_file = os.path.join(output_path, 'extracted_texts.json')
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(extracted_texts, f, ensure_ascii=False, indent=4)

print(f"Completed processing {processed_files} PDFs.")
print(f"Extracted text saved to: {output_file}")

import os
import pdfplumber

# Function to extract text from a single PDF
def extract_pdf_text(pdf_path):
    try:
        with pdfplumber.open(pdf_path) as pdf:
            text = ''
            for page in pdf.pages:
                page_text = page.extract_text() or ''  # Handle pages with no text
                text += page_text
            return text
    except Exception as e:
        print(f"Error processing file {pdf_path}: {e}")
        return None

# Define the directory containing PDFs
directory_path = '/content/drive/MyDrive/EntireDataset'  # Update with the correct path to your PDFs

# List to hold extracted texts
pdf_texts = []

# Extract text from each PDF and store in pdf_texts list
for file_name in os.listdir(directory_path):
    if file_name.endswith('.pdf'):  # Ensure it's a PDF
        file_path = os.path.join(directory_path, file_name)
        print(f"Processing: {file_name}")

        # Extract text
        pdf_text = extract_pdf_text(file_path)
        if pdf_text:
            pdf_texts.append(pdf_text)

# Print the first extracted text for verification
print(pdf_texts[0])  # Print first extracted text

"""# Libraries"""

!pip install nltk spacy
!python -m spacy download en_core_web_sm

"""## Pre Process"""

import nltk
import spacy
import re
from nltk.corpus import stopwords
import json

# Download NLTK stopwords if not already downloaded
nltk.download('stopwords')

# Initialize SpaCy model
nlp = spacy.load('en_core_web_sm')

# Function to clean and preprocess the text
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()

    # Remove special characters and numbers (keep only alphabets and spaces)
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Tokenize the text using SpaCy
    doc = nlp(text)

    # Remove stopwords and lemmatize the words
    processed_tokens = [
        token.lemma_ for token in doc if token.lemma_ not in stopwords.words('english') and len(token.lemma_) > 1
    ]

    # Join the tokens back into a string
    return ' '.join(processed_tokens)

# Load the extracted texts from the JSON file
input_json_file = '/content/drive/MyDrive/ExtractedText/extracted_texts.json'

with open(input_json_file, 'r', encoding='utf-8') as f:
    extracted_texts = json.load(f)

# Apply preprocessing to each extracted text
processed_texts = {filename: preprocess_text(text) for filename, text in extracted_texts.items()}

# Verify by printing the processed text of one of the PDFs
print(processed_texts["General Studies Paper II_E-Book-107.pdf"][:500])  # Display first 500 characters of the processed text from one PDF

"""# Load the Processed text"""

import json

# Load the processed text from the JSON file
processed_json_file = '/content/drive/MyDrive/ExtractedText/processed_texts.json'

with open(processed_json_file, 'r', encoding='utf-8') as f:
    processed_texts = json.load(f)

# Verify the processed text for one of the PDFs
print(processed_texts["General Studies Paper II_E-Book-107.pdf"][:500])  # Display first 500 characters of processed text

"""# LAbel the data"""

def label_document(text):
    # Define categories and their associated keywords
    categories = {         "Art & Culture": [    "art"
"cultural"
"architecture"
"temple"
"literature"

        ],

        "Modern History": [

           "army", "famine", "nationalist", "mutiny", "chandra", "congress", "curzon", "noncooperation", "reformer", "panipat", "samaj", "pala",
           "indenture", "bose", "revolutionary", "leadership", "transfer", "brahmo", "colony", "armed", "dalhousie", "arab", "gandhis",
           "mideighteenth", "eic", "chinese", "soldier", "aspiration", "indians", "partition", "naval", "inc", "ideological", "voice", "imperial",
           "subhash", "satyagraha", "radical", "selfreliance", "ultimately", "absence", "dalit", "league", "complicate", "besant", "socioreligious",
           "constructive", "drain", "turning", "deindustrialization", "european", "negotiation", "quit", "join", "female", "boycott", "annie",
           "rationalism", "abolition", "roy", "examine", "nineteenth", "strand", "mobilization", "march", "socialist", "worker", "eventual", "defy",
           "territory", "bombay", "lapse", "remarriage", "ram", "mohan", "downtrodden", "empireshaking", "afghan", "culmination", "recurrent",
           "precede", "polity", "tibet", "viceroy", "tenure", "compete", "till", "fragmented", "cheap", "reconstruction", "nail", "coffin", "navy",
           "loyalty", "descendant", "ineffective", "passive", "avoid", "scenario", "alternative", "peasant", "sarojini", "naidu", "kamala", "aruna",
           "asaf", "ali", "champion", "orthodoxy", "humanism", "legislative", "bal", "gangadhar", "tilak", "telegraph", "communication", "postal",

           "province", "sudden", "situation", "devastating", "permanent", "improvement", "slow", "khadi", "secularism", "citizen", "awakening",
           "ishwar", "vidyasagar", "phule", "purdah", "untouchability", "party", "terrain", "maratha", "dominance", "watershed", "separate",
           "derozian", "sen", "hundred", "peasantry", "amelioration", "officer", "garner", "monastic", "impoverishment", "equip", "superior",
           "plassey", "advantage", "nivedita", "aurobindo", "hume", "french", "weak", "reconstruct", "topic", "vacuum", "instability", "carry",
           "conviction", "assertive", "militant", "decisive", "ina", "ii", "alongside", "persuasion", "counterfactual", "faction", "momentum",
           "galvanize", "communist", "subhas", "bhagat", "singh", "chandrashekhar", "azad", "identitybase", "rani", "bhikaji", "cama", "initially",
           "expose", "petition", "council", "bipin", "pal", "lala", "lajpat", "rai", "guidance", "maintenance", "deny", "spurt", "occurrence", "bihar",
           "ryotwari", "cash", "imbalance", "put", "capacity", "democracy", "infanticide", "fulfil", "jyotirao", "ahmad", "argue", "eradicate",
           "harijan", "republican", "equitable", "oppress", "shah", "artillery", "grant", "direct", "politically", "recruitment", "servant",
           "landowner", "loyal", "withdraw", "eliminate", "keshub", "opposition", "impose", "resentment", "annexation", "princely", "swami",
           "vivekananda", "selfrespect", "small", "russian", "cooperative", "modernize", "broaden", "khilafat", "vikramashila", "farreache",
           "northwest", "chitral", "construct", "troop", "mid", "eighteenth", "britain", "smallscale", "finance", "consistently", "diplomacy",
           "espionage", "mistrust", "nizam", "disadvantage", "mercenary", "dependency", "sister", "mira", "alfassa", "mother", "governorgeneral",
           "turbulent", "cripps", "simla", "conference", "disagreement", "unable", "mountbatten", "traveller", "hsuan", "tsang", "albiruni", "able",
           "historian", "torch", "bearer", "prohibition", "alcohol", "drug", "effectiveness", "abolish", "slavery", "indentured", "trinidad", "tobago",
           "subsection", "majority", "cripple", "markedly", "employing", "elect", "president", "twice", "bloc", "compel", "legitimate", "relinquish",
           "generally", "germany", "italy", "japan", "japanese", "widely", "charismatic", "manage", "cornerstone", "nationalists", "convergence",
           "peak", "lakshmibai", "jhansi", "chennamma", "kittur", "begum", "hazrat", "mahal", "picketing", "burning", "picket", "liquor", "shop",
           "kalpana", "datta", "pritilata", "waddedar", "underground", "confrontation", "usha", "mehta", "sucheta", "kriplani", "clandestine",
           "radio", "camp", "fighter", "foreigner", "homeland", "irishborn", "theosophist", "activist", "thinker", "consist", "expansive",
           "consciousness", "resolution", "opinion", "newspaper", "amrita", "bazar", "patrika", "conducive", "morleyminto", "programme", "biological",
           "heir", "thane", "proponent", "calcutta", "madra", "pwd", "postage", "appointment", "lieutenant", "governor", "note", "unpopular",

           "severity", "subsistence", "disastrous", "starvation", "burden", "incentive", "madras", "commercialization", "indigo", "opium",
           "comparatively", "extract", "deplete", "theory", "dadabhai", "naoroji", "extraction", "worsen", "berar", "stagnation", "simply", "dandi",
           "contraband", "monopoly", "handwoven", "cloth", "charkha", "defiance", "kasturba", "vohra", "emancipation", "pluralistic", "decisionmake",
           "accountability", "transparency", "furthermore", "question", "forefront", "rectify", "adversely", "vehemently", "oppose", "enactment",
           "illegal", "infant", "kill", "shortly", "inhuman", "consent", "remarry", "savitribai", "sir", "sye", "confine", "stifle", "inheritance",
           "sevak", "sangh", "jurist", "economist", "firsthand", "chief", "outlaw", "federation", "disagree", "durrani", "trunk", "kilometer",
           "mile", "flat", "scale", "cavalry", "obstruction", "maneuver", "commander", "dissolve", "crown", "secretary", "economiccentric",
           "reorganization", "restructure", "prevent", "reorganize", "dispossession", "reformist", "offend", "instruction", "westernstyle",
           "reference", "henry", "louis", "vivian", "derozio", "modernity", "liberty", "fraternity", "purify", "superstition", "monotheism",
           "debendranath", "advocacy", "polygamy", "assault", "rumor", "cow", "pig", "fat", "enfield", "rifle", "cartridge", "anger", "forcibly",
           "absorb", "deposition", "bahadur", "oudh", "awadh", "paika", "vellore", "linkage", "ill", "harmful", "instill", "rediscovery",
           "westerneducate", "arya", "theosophical", "socialism", "communism", "cpi", "ev", "ramasamy", "castebased", "electorate", "allindia",
           "communalization", "contradictory", "big", "sepoy", "impoverish", "unrest", "sanyasi", "kol", "interesting", "unifying", "cohesion",
           "lean", "sympathy", "vallabhbhai", "patel", "assume", "uncertain", "whether", "legitimacy", "crafting", "humanity", "fear", "cease",
           "agree", "pay", "indemnity", "tool", "exert", "acquire", "middle", "hindustan", "hsra", "patriotism", "dharmapala", "devapala", "devout",
           "mahayana", "vajrayana", "impetus", "deepening", "odantapuri", "proliferation", "monk", "survival", "dynastys", "reunification",
           "frontier", "britishoccupied", "peshawar", "khyber", "khur", "waziristan", "abdur", "rahman", "turkey", "combination", "mahalwari",
           "landholder", "indebtedness", "manufacture", "handicraft", "machine", "sufficiency", "repatriation", "profit", "salary", "pension",
           "official", "payment", "loan", "outweigh", "detrimental", "mostly", "comprise", "win", "paradox", "superiority", "outnumber",
           "victorious", "ally", "defeat", "conspire", "highranke", "sirajuddaulahs", "rivalry", "anglomysore", "marathas", "ambition",

           "tipu", "overextend", "flintlock", "musket", "outdate", "equipment", "wandiwash", "paymaster", "bulk", "manpower", "wellorganize",
           "diplomatic", "colonize", "closure", "increasingly", "landholding", "fluctuation", "spend", "impede", "respected", "disintegration",
           "crippled", "twenty", "selfgovernment", "disciple", "ghosh", "bagha", "jatin", "lecture", "allan", "octavian", "collaborator", "abroad",
           "founder", "drawback", "james", "andrew", "brounramsay", "series", "shaping", "annex", "die", "istory", "challenging", "negotiate",
           "proposal", "wavell", "parity", "furth", "cabinet", "federal", "outbreak", "dominion", "hurried", "poorly", "fahien", "travelogue",
           "outsider", "inherent", "bias", "vested", "ibn", "battuta", "huan", "currency", "february", "sailor", "racial", "police", "states",
           "soviet", "union", "postwwii", "contradict", "selfdetermination", "immediate", "acceleration", "convince", "feasible", "transcend",
           "intermarriage", "clarify", "beset", "spectre", "successor", "centralized", "steady", "deccan", "sikh", "rajasthan", "nawab", "fragment",

           "shortlive", "temporary", "convenience", "constantly", "lasting", "recap", "nationbuilde", "stimulate", "diminish", "handloom",
           "hindumuslim", "symbolically", "unjust", "potency", "concentrate", "endorse", "temperance", "curb", "addiction", "dowry", "rally",
           "enumerate", "epoch", "auspex", "staunch", "supplementary", "picture", "china", "mainly", "huge", "willing", "overseas", "familiar",
           "circumstance", "mosque", "sikhism", "fiji", "mauritius", "guyana", "roti", "curry", "merge", "proclaim", "late", "agitation",
           "memorandum", "speech", "want", "extremism", "disillusion", "extremist", "dilute", "repression", "repressive"
        ],

        "Post-Independence India": [
         "slogan", "jai", "tashkent", "gramdan", "bhoodan", "bangladesh", "landlessness", "jawan", "kisan", "sociocultural", "success",
         "constituent", "problem", "maulana", "indopak", "humanitarian", "ask", "minister", "bureaucratic", "regionalism", "presidency",
         "acharya", "vinoba", "bhave", "landless", "interstate", "allocation", "midnineteenth", "uttarakhand", "telangana", "kalam", "preand",
         "postindependent", "akademi", "donation", "prompt", "geopolitical", "draft", "modification", "integrity", "departure", "hail", "shastri",
         "milestone", "newlyindependent", "mysore", "refugee", "apply", "injustice", "minimalism", "enact", "andhra", "northeastern", "twonation",
         "assessment", "voluntary", "redistribution", "ownership", "ceasefire", "prewar", "prisoner", "noninterference", "affair", "normalize",
         "compulsion", "bangladeshs", "strain", "partly", "donate", "mixed", "rationale", "shortterm", "drafting", "directive", "directive", "newly",


         "second", "lal", "vigyan", "technologys", "rallying", "cry", "decentralization", "unification", "autonomous", "polo", "newlyjoine", "travancore",
         "baroda", "jurisdictional", "claim", "junagadh", "ethnicity", "minority", "indicator", "pro", "con", "carefully", "homogeneous", "federalism",
         "parochialism", "sharing", "friction", "polarization", "spill", "serious", "developmental", "resolve", "throw", "ahimsa", "urge", "aggression",
         "misinformation", "fake", "propaganda", "adhere", "honesty", "entire", "selfreliant", "thinking", "consumerdriven", "possession", "meaningful",
         "remind", "cite", "broadly", "reorganisation", "ss", "meghalaya", "mizoram", "uttar", "officially", "bifurcation", "ladakh", "pre",
         "preindependent", "jinnahs", "journalism", "journalist", "writer", "alhilal", "ugc", "sahitya", "lalit", "kala", "sangeet", "natak",
         "un", "kosygin", "mediate", "withdrawal", "respective", "deescalation", "sever", "return", "neither", "sovereignty", "outstanding",
         "underlie", "deescalate", "brutal", "crackdown", "pakistani", "bengalispeake", "flee", "escape", "persecution", "catastrophe", "pakistans",
         "rival", "liberation", "counterbalance", "persuade", "voluntarily", "portion", "particular", "expect", "villager", "gram", "actual",
         "redistribute", "reluctance", "infertile", "insufficient", "landowning", "enthusiasm", "wane", "ceiling", "away", "analyse", "underlying",
         "skirmish", "rann", "kutch", "fullscale", "indiapakistan", "escalation", "mind", "wellrounde", "positively", "roadmap", "beneficial",
         "revolve", "delivery", "efficiently", "deliver", "policymake", "motivate", "infrastructural",
         "entail", "requirement", "assemblys", "feat", "provincial", "legislator", "machinery", "ias", "judiciary", "supreme", "suit"
        ],
        "World History": [
            "american", "industrialization", "england", "nep", "anticolonial", "decolonization", "suez", "germanys", "regime",
            "malaysia", "mercantilism", "appeasement", "malay", "totalitarian", "artificial", "hitler", "singapore", "selfimage",
            "westerneducated", "scramble", "mercantilist", "colonist", "solely", "japans", "meiji", "nazi", "austriahungary", "germane",
            "multifaceted", "monarchy", "nations", "stratification", "panafricanism", "nationalization", "israel", "latecomer", "zaibatsu",
            "berlin", "expansionist", "treaty", "versaille", "check", "commonality", "napoleon", "lenin", "capitalism", "favorable", "steam",
            "engine", "overcrowd", "harsh", "industrialize", "regulatory", "remove", "tripartite", "collusion", "invade", "motive", "disregard",
            "selfinterest", "enforce", "enterprise", "selective", "borrowing", "maximize", "feudal", "quest", "statement", "interwar", "suppress",

            "adolf", "weakness", "chop", "artificially", "continent", "sole", "oversimplification", "militarism", "imperialism", "cheque", "modernday",
            "malays", "organisation", "umno", "allegation", "cronyism", "authoritarianism", "neighbor", "borneo", "spratly", "merger", "malaya",
            "expulsion", "contentious", "revisionism", "rewrite", "reinterpret", "suppression", "riot", "glorification", "concert", "philosopher",
            "john", "locke", "montesquieu", "rousseau", "inform", "contract", "bill", "branch", "dominate", "collapse", "absolutism", "landmark",
            "enshrine", "send", "shockwave", "intervene", "unef", "pound", "monetary", "imf", "repercussion", "anthony", "eden", "resign", "imperialist",
            "curtail", "inability", "unilaterally", "soon", "vladimir", "mix", "coal", "ore", "nonagricultural", "banking", "spinning", "jenny", "hour",
            "dangerous", "factory", "wealthy", "capitalist", "proper", "analysis", "toward", "prosperous", "subordinate", "colonialism", "broadcast",
            "disseminate", "kwame", "nkrumah", "ghana", "lopold", "sdar", "senghor", "senegal", "postcolonial", "capability", "embody", "irish", "charter",
            "specifically", "regressive", "interconnect", "shatter", "aswan", "secret", "regain", "nasser", "october", "pretext", "europeandrawn",
            "ignore", "cohesive", "thirteen", "true", "motivation", "accumulation", "reliant", "stamp", "townshend", "merchant", "frustrate",
            "restriction", "tightly", "room", "frame", "authoritarian", "consensusbuilde", "constituency", "fabian", "rooted", "necessitate",
            "apex", "topdown", "shogunate", "modernization", "catalyst", "shake", "footing", "amid", "rapidly", "cope", "fascism", "benito",
            "mussolinis", "fascist", "dissent", "nazism", "seize", "antisemitism", "joseph", "stalin", "consolidation", "strengthening", "destabilize",
            "munich", "czechoslovakia", "weakening", "investing", "stateowned", "conglomerate", "workforce", "nationbuilding", "formalize",
            "inaccurate", "map", "devastate", "reshape", "ottoman", "bulgaria", "assassination",
            "archduke", "franz", "ferdinand", "unconditional", "poland", "declaration", "unresolved", "undoubtedly", "shackle", "converge"
        ],

        "Indian Society": [
           "sex", "sect", "ratio", "tier", "gig", "deprivation", "care", "cryptocurrency", "crypto", "core", "patriarchy", "ie", "article",
           "outside", "elderly", "person", "earn", "covid", "pluralism", "whereby", "reproductive", "feeling", "membership", "accept", "bad",
           "assertiveness", "decide", "feminization", "religiosity", "asset", "upper", "homogenization", "try", "assertion", "ban", "relative",
           "interdependence", "flow", "scarce", "salience", "essentially", "flexibility", "migrate", "nuclear", "crime", "globalized", "treat",
           "sexual", "scs", "aged", "coexist", "stereotype", "coexistence", "travel", "annihilation", "notion", "harassment", "feminist", "demographic",
           "enough", "almost", "obscurantism", "gujarat", "northern", "easily", "globe", "inevitable", "religiousness", "making", "plurality", "mode",
           "multireligious", "diwali", "consumer", "fulfill", "ease", "index", "transaction", "recently", "attack", "speedy", "unequal", "blindly",
           "immemorial", "misuse", "shall", "equally", "remedy", "offense", "alone", "parliament", "contraceptive", "sts", "renew", "totally", "manual",
           "backward", "convert", "manifest", "anything", "whereas", "atrocity", "employee", "tenet", "aware", "reap", "triple", "talaq", "visavis",
           "complementary", "sarva", "disturb", "christianity", "wfh", "size", "disposable", "indore", "ecommerce", "attractive", "hospitality",
           "store", "ukraine", "uncertainty", "averse", "homogenisation", "wipeout", "mcdonaldization", "dressing", "nuclearization", "amendment",
           "stop", "intrareligious", "swayam", "replacement", "alive", "peculiar", "informed", "discriminate", "absolutely", "trait", "arrangement",
           "deprive", "expensive", "completely", "smart", "selection", "boy", "uniqueness", "pinkcollar", "dichotomy", "already", "glocal", "least",
           "productive", "seem", "sc", "specificity", "likely", "target", "postcovid", "accumulate", "electronic", "appear", "unfairly", "elsewhere",
           "something", "eradication", "trap", "discriminatory", "getting", "bar", "dress", "sdg", "abhiyaan", "entry", "thing", "husband", "oxfam",
           "lower", "feed", "visvis", "office", "populationrelated", "interpret", "respectful", "eid", "worklife", "ahmedabad", "vadodara", "coimbatore",
           "pune", "whitecollar", "surat", "affordability", "top", "investor", "consume", "transport", "marked", "brain", "ruralurban", "boon", "ai",
           "truly", "beggar", "sovereign", "negatively", "digitally", "illiterate", "disproportionate", "charge", "collect", "perhaps", "son",
           "transnational", "corporation", "unmonitored", "misrepresentation", "domain", "artsmovie", "affinity", "preamble", "differently",
           "interreligious", "pathshala", "portal", "pupilteacher", "version", "correct", "peacefully", "glow", "adjust", "populous", "rehabilitation",
           "actually", "tremendous", "geography", "mere", "prior", "interdisciplinary", "mutually", "tkdl", "repository", "homemaker", "night",
           "untouchable", "deliberately", "discourage", "middleclass", "fully", "unplanned", "notice", "traffic", "inclusion", "capita", "earner",
           "inherit", "attach", "bride", "postnatal", "tfr", "spouse", "backwardness", "focused", "lfpr", "deem", "glass", "workplace", "rd",
           "awaken", "nutrition", "mortality", "testing", "revivalism", "favorite", "illustration", "rank", "scavenging", "lingayat", "christians",
           "ict", "econtent", "exception", "marry", "literacy", "foremost", "counterpart", "apt", "kind", "nursing", "taboo", "objectification",
           "infinite", "vidarbha", "cap", "flaw", "suffer", "mainstay", "user", "maximum", "reduction", "component", "constraint", "retirement",
           "maternity", "strictly", "mismatch", "metropolitan", "viceversa", "chronic", "enjoyment", "treated", "regionally", "discussion", "expectancy",
           "inflation", "shock", "sideline", "subdue", "hype", "copy", "april", "freely", "localize", "rid", "derogatory", "absolute", "gorkhaland",
           "following", "cent", "sexually", "pregnancy", "dividend", "june", "multilingual", "multicaste", "liberate", "mgnrega", "shiksha", "primitive",
           "abandon", "sabarimala", "celebration", "matriarchal", "disadvantaged", "nontribal", "ancestor", "notwithstanding", "monitor", "childrearing",
           "wife", "grandparent", "hire", "ilo", "suitably", "crore", "semiskille", "frustration", "anywhere", "whole", "stri", "sangathana", "ela",
           "specify", "sectarianism", "iskcon", "expenditure", "contraception", "educator", "sabka", "multidimensional", "enculturation", "obedience",
           "sambhava", "sr", "bommai", "sambhav", "vasudhaiva", "kutumbakam", "phrase", "maha", "upanishad", "nirapekshata", "christmas", "fervor",
           "invader", "rest", "strongly", "amber", "prune", "upcoming", "varanasi", "lpg", "calicut", "eol", "namely", "crowd", "brand", "footfall",
           "standup", "mudra", "jam", "trinity",
           "udan", "ladder", "hostel", "guest", "recreation", "handful", "semi", "lucknow", "bhubaneshwar", "gurugram", "flock",
           "stressful", "inevitability", "latenight", "affluence", "parallelly", "evetease", "cloud", "intelligence", "cybersecurity",
           "evenly", "distribute", "inculcate", "cryptography", "blockchain", "computerized", "database", "bypass", "transacting", "speed",
           "dollar", "ukrainian", "stock", "cryptocurrencie", "terrorist", "cartel", "launderer", "nascent", "cryptos", "amateur", "cryptoexchange",
           "behavior", "fad", "volatile", "transact", "receiver", "remittance", "save", "extortion", "ransomware", "wannacry", "ransom", "cyber",
           "scam", "inherently", "quickly", "illconceive", "driver", "agenda", "ought", "commodity", "greatness", "individualisation",
           "individualized", "lining", "opening", "differentiate", "existent", "realm", "pull", "curtain", "evidya", "digitalonlineon",
           "multimode", "daisy", "schooling", "nio", "differentlyable", "remotest", "arena", "multidisciplinary", "costeffective", "commute",
           "considerably", "elearne", "nuisance", "bpl", "academic", "allround", "elearning", "aggravate", "schoolbase", "pitch", "radically",
           "uniquely", "universe", "creationwhich", "individuality", "assimilate", "indianize", "innate", "casteism", "genius", "empowering",
           "includes", "habitation", "fra", "recognise", "forestdwelle", "thread", "aryan", "welcome", "incoming", "permanently", "beautiful",
           "premise", "akbar", "tolerant", "intermix", "isis", "naxal", "infect", "indoctrinate", "devadasi", "tightrope", "volume", "beneficiary",
           "participant", "planner", "solve", "fighting", "tsunami", "book", "specialization", "bifurcate", "nonexclusionary", "equity", "mainstreams",
           "mire", "patent", "exclusive", "vestige", "expanse", "gamechanger", "iks", "cell", "ministry", "definition", "parttime", "amazon", "flipkart", "exit",
           "ondemand", "dropout", "complement", "workfromhome", "sale", "sizable", "woo", "wing", "adi", "dravidas", "oppressed", "shri", "narayana", "paripalana",
           "sndp", "pervade", "angle", "car", "therefore", "mileage", "unnecessary", "sewage", "quantity", "garbage", "bhalswa", "ghazipur", "landfill", "physically",
           "maid", "meager", "prone", "overcrowding", "anonymous", "proliferate", "juvenile", "delinquency", "inevitably", "systematic", "cities", "amrut", "collaborate",
           "perpetuation", "cult", "misandry", "psyche", "badly", "sonpreference", "bodily", "lone", "criminal", "drastic", "sexselective", "abortion", "stay", "split", "lifecycle",
           "individualization", "materialistic", "dependability", "andrule", "religionbased", "opportunism", "communalist", "jinnah", "election", "sufficiently", "selfintrospect", "blame",
           "anyone", "marginally", "misery", "decommunalization", "let", "aligned", "feasibility", "uniformity", "motherhood", "penalty", "unpaid", "childcare", "commodification", "docile", "buy",
           "pink", "collar", "fit", "nurse", "receptionist", "babysitter", "lecturer", "mediarelate", "upward", "managementlevel", "mandate", "sarpanch", "pati", "affirmative", "induct", "disassociate",
           "stigma", "sexuality", "budgeting", "respite", "remember", "jl", "valid", "realize", "debatable", "alleviate", "liability", "parameter", "segment", "matriarchy", "excess", "deficit", "willingness",
           "educated", "prenatal", "reduced", "borrow", "brideprice", "reinterpretation", "mcdonald", "vegetarian", "chicken", "beef", "protectionist", "quite", "helpful", "vanish", "performer", "speciality",
           "pashmina", "phulkari", "brass", "bamboo", "economical", "foodshare", "subdivision", "bahujan", "samajwadi", "coach", "exam", "oligarch", "patidar", "landowne", "jat", "disappear", "subtle", "advertisement",
           "ceremonial", "cemetery", "ideate", "hashtag", "twitter", "video", "greet", "etiquette", "wash", "prostrating", "suppose", "seriously", "option", "gigantic", "nmeict", "learner", "postgraduate", "prabha", "dth",
           "clock", "ndl", "singlewindow", "diksha", "tone", "homebound", "homemake", "livestock", "husbandry", "capable", "distant", "fade", "carrier", "render", "obsolete", "overwork", "illness", "etch", "clash",
           "hinterland", "konkan",
           "ricefish", "continuum", "shirt", "pajama", "turban", "dhoti", "locally", "district", "ethnolinguistic", "sikkim", "sikkimbuddhist", "nepalibrahminhindus", "monolithic", "accusation",
           "witchcraft", "disrobe", "defile", "cognizable",
           "anticipatory", "bail", "trial", "seamlessly", "general", "muslims", "multiplicity", "lithium", "gadget", "waterscarce", "satisfy", "waterscarcity", "specialize", "nonrenewable", "fossil", "customer", "interoperability", "extra", "rewarding",
           "consult", "marketing", "lucrative", "purely", "certainty", "replaceable", "employer", "flexiworker", "entitle", "insurance", "pf", "gradepay", "plus", "allowance", "upskille", "gainfully", "routinely", "gigeconomy", "upgrade", "moveup", "organizational",
           "demandsupply", "depress", "predictable", "formal", "upskilling", "documentation", "supportive", "computer", "player", "noida", "ancillary", "cmie", "shrink", "anganwadi", "aser", "onethird", "garib", "kalyan", "anna", "atmanirbhar", "undo", "certainly", "voter",
           "genuine", "elaboration", "linguistically", "goan", "konkani", "belgaum", "tug", "marathi", "bengali", "assamese", "cooking", "flavour", "holi", "interact", "parsi", "really", "pandit", "vendetta", "credibility", "none", "congenial", "genderbased",
           "properly", "guard", "induction", "double", "commercialize", "unaffordable", "seclude", "homenurse", "saving", "reluctant", "decent", "dive", "depth", "delve", "petty", "obstacle", "homogenize", "culturally", "incompatible", "antagonistic", "hostile", "maybe",
           "typical", "construe", "blatantly", "mothersinlaw", "wish", "unempowere", "powerless", "refuse", "unwanted", "nonavailability", "slightly", "maternal", "forceful", "lawbase", "elimination", "stabilization", "insert", "morality", "misguided", "popularly", "homogenous", "halloween", "diya", "uno", "chhath",
           "puja", "silicon", "attached", "mixture", "associational", "penetrate", "rescue", "unemployed", "reel", "roll", "adult", "samagra", "awas", "pmay", "misinterpretation", "rejection", "antireligion", "saffron", "beard", "pat", "skull", "taqiyah", "fundamentalist", "infringement", "bursting", "cracker",
           "jallikattu", "meat", "interrupt", "slaughter", "declare", "unlawful", "manipulation", "sake", "perfect", "obvious", "misleading", "judge", "representative", "unanimity", "pick", "isolated", "multi", "storey", "mini", "miniindia", "dosa", "breakfast", "ubiquitous", "naanparatha", "dinner",
           "ganpati", "utsav", "ten", "makar", "sankranti", "kite", "fly", "pongal", "hometown", "race", "extracurricular", "uncountable", "validate", "superpower", "glue", "bind", "onesixth", "emanate", "hegemonic", "supporter", "perpetrator", "sufferer", "malnutrition", "westernization",
           "virtuous", "categorization", "numerically", "ethnographic", "monogamous", "polygamous", "worshipper", "polytheist", "polyandrous", "khasis", "jarawas", "count", "endogamy", "happily", "satisfaction", "categorize", "eat", "behave",
           "clearly", "myth", "blind", "genital", "mutilation", "fgm", "practise", "nikah", "halala", "propagate", "illogical", "unreasonable", "board", "virginity", "iraq", "rape", "kyrgyzstan", "violate", "haji", "lgbt", "tend",
           "homosexuality", "distancing", "vaccine", "hesitancy", "vaccination", "economiesofscale", "daycare", "nsso", "engaged", "cultivator", "lowpaid", "irregular", "supplement", "familys", "domination", "aspirational", "stopper", "precondition", "childbirth", "rearing", "extremely",
           "earning", "undervaluation", "grade", "ironical", "frown", "sdgs", "niti", "aayog", "casteization", "politicization", "todays", "rogue", "flare", "castefree", "scavenge", "surviving", "socalled", "subtler", "clue", "suffering", "accelerated", "quote",
           "widening", "suggestion", "alarmingly", "destabilizing", "bottom", "virus", "undp", "forum", "bluecollar", "street", "vendor", "slide", "fao", "hisher", "habitual", "residence", "unskilled", "canada", "unskilledsemiskilled", "inside", "rationally",
           "disturbance", "provocative", "credential", "unblemished", "diaspora", "occasional", "hatred", "destructive", "distinguish", "religiousnessreligiosity", "latter", "uproot", "totality",
           "freeindia", "sow", "bore", "bitter", "pain", "unease", "bitterness", "heart", "ensue", "riots", "ayodhya", "godhra", "jarnail", "bhindranwale", "panel", "pharmaceutical", "curse", "captive", "extravagant", "developed", "owner", "zerosum", "technonationalism", "techno", "iot", "integral", "swiftly", "ambitious",
           "technocolonialism", "intergenerational", "naturecentere", "contractor", "overexploitation", "rigorous", "refining", "questioning", "verification", "saheli", "manushi", "shakti", "mukti", "pennurimai", "iyyakam", "underprivileged", "pandita", "ramabai", "kamini", "sarala", "chaudhurani", "medha", "patkar", "bhatt",
           "madhu", "kishwar", "scavenger", "unorganized", "brunt", "inaccessible", "coverage", "perpetrate", "shramik", "mahila", "adulteration", "bhatts", "sewa", "intersectional", "appropriately", "established", "illeffect", "subdivide", "select", "shaikh", "subsect", "siddiqui", "farooqi", "usmani", "abbasi", "subcaste", "shia", "sunni",
           "krishna", "institutionalize", "became", "moderated", "husbandwife", "parentchildren", "consciously", "requisite", "workspace", "blur", "blurred", "negligence", "routine", "dramatically", "week", "trauma", "ncw", "data", "register", "complaint", "nationwide", "lockdown", "confinement", "likelihood", "unintended", "infection", "explicitly",
           "announce", "stabilize", "desirable", "asha", "biology", "outreach", "adolescent", "television", "bane", "maker", "devise", "legitimize", "industrialisation", "qualification", "identification", "deduce", "broadminde", "disrespectful", "violative", "restaurant", "shopping",
           "mall", "irrelevant", "criterion", "notification", "employmentrelate",
           "lok", "ncst", "oversee", "sath", "inequity", "superficially", "pronounce", "incidence", "nfsa", "nrlm", "poshan", "persistence", "tendulkar", "committee", "rs", "amartya", "steadily", "optimally", "jobseeker", "match", "dent", "hunger", "diverge", "excessive", "selfish"
        ],

        "Geography": [
          "plate", "futuristic", "arctic", "salinity", "volcanic", "summary",
          "corridor", "eruption", "continental", "interlink", "strait", "oceanic", "dead",
          "volcano", "isthmus", "pacific", "greenhouse", "emission", "slope", "circulation", "aquaculture",
          "delta", "sugar", "rubber", "shale", "manufacturing", "desertification", "refinery", "mantle", "himachal",
          "inversion", "plume", "el", "intensity", "nino", "america", "rainwater", "subduction", "uranium", "irns", "collision",
          "atlantic", "nutrient", "pisciculture", "hemisphere", "beneath", "sediment", "cryosphere", "mill", "darjeele", "iwt", "shipping",
          "density", "atmospheric", "stream", "drift", "permafrost", "frequency", "magma", "archipelago", "juno", "jupiter", "producer",
          "minimize", "gw", "congestion", "interlinking", "reclamation", "landslides", "gradient", "rotation", "landuse", "moisture", "mexico",
          "layer", "predict", "bilateral", "humidity", "petroleum", "application", "microwatershe", "semiarid", "subsidy", "hydropower", "circumpacific",
          "contributor", "coriolis", "topography", "scientist", "indonesian", "unusual", "margin", "shivalik", "planter", "thorium", "brackish", "regulate",
          "tap", "magnetic", "hydroelectric", "sugarcane", "instal", "tropic", "polluted", "meter", "mountainous", "encroachment", "methane", "brazil",
          "crystal", "afforestation", "symptom", "geographic", "vehicle", "shear", "sedimentation", "denser", "atomic", "northwestern", "fahrenheit", "gps",
          "geophysical", "rooftop", "turbine", "kenbetwa", "hit", "aquatic", "lava", "percentage", "eurasian", "stormwater", "reservoir", "downstream",
          "destroy", "circum", "affected", "humid", "alp", "intrusive", "extrusive", "mechanism", "policymaker", "discovery", "nearby", "rotate",
          "lithosphere", "landmass", "affordable", "adjacent", "fog", "variability", "carrying", "recharge", "cubic", "fragile", "bleaching",
          "equator", "agrobase", "macroclimatic", "logistic", "mandatory", "spring", "timber", "footprint", "caribbean", "remedial", "timeconsuming",
          "waterway", "finish", "insolation", "damaging", "related", "particle", "toxic", "respiratory", "gross", "unstable", "saturate", "ship",
          "thunderstorm", "anthropogenic", "debris", "retention", "sheet", "seismic", "colorcoded", "precaution", "sustainably", "shadow", "molten",
          "coarsegraine", "finegraine", "commonly", "texture", "cooling", "geologically", "satellite", "keen", "prabhari", "algae", "virtually", "burn",
          "hurricane", "evaporation", "sensitive", "breakup", "volcanism", "floor", "biotechnology", "synthetic", "frictional", "upwelle", "australia",
          "humaninduce", "happening", "elnino", "upwelling", "wet", "uhi", "welldevelope", "quarter", "ecology", "profitability", "desalination",
          "localisation",
          "barrage", "allweather", "macro",
          "polar", "succeed", "september", "rainy", "km", "leather", "cbm", "navigational", "albedo", "geothermal"
        ],

        "Polity and Constitution": [
           "ordinance", "tribunal", "eci", "disqualification", "attorneygeneral", "activism", "promulgate", "simultaneous", "disqualify", "lt",
           "mcc", "ucc", "arbitration", "parliamentarian", "cbi", "voting", "ncbc", "centralization", "evms", "whistleblower", "mercy", "chairman",
           "void", "corrupt", "concurrent", "devolution", "nct", "samitis", "pil", "constitutionalization", "drpsc", "rpa", "lg", "arbitral", "tussle",
           "advice", "vvpat", "coelho", "ncsc", "repromulgation", "validity", "epidemic", "quasijudicial", "occasion", "sentence", "naga", "cbis",
           "presidential", "hear", "indira", "drpscs", "performancebase", "codification", "award", "judgement", "controversy", "hate", "pardon",
           "critique", "educationally", "narain", "guilty", "clarity", "arbitrator", "confidentiality", "firecracker", "minerva", "overstep", "ninth",
           "legislate", "vicepresident", "interpreting", "aggrieved", "polluter", "noconfidence", "toe", "never", "ngt", "sfc", "functionary", "conciliation",
           "deadlock", "nonpartisan", "pende", "impeachment", "frivolous", "trustworthiness", "disclosure", "false", "slip", "nota", "interfere", "adjective",
           "defection", "convict", "contradiction", "encroach", "relax", "locus", "standi", "behalf", "litigation", "withhold", "objection", "seventh",
           "citizenship", "obc", "summon", "approve", "discretionary", "wadhwa", "twothird", "hasty", "deterrence", "precautionary", "intent", "clause",
           "consensual", "aa", "enmity", "override", "violator", "objectivity", "cat", "appellate", "tdsat", "responsibly", "propriety", "surveillance",
           "normally", "guardian", "nonmoney", "separately", "quasifederal", "whistleblowe", "chilling", "malfunctioning", "paper", "keshavananda",
           "arbitrarily", "devolve", "incite", "adviser", "pris", "constitutionalize", "useless", "stepney", "tyre", "organ", "unitarism", "transitional",
           "antithetical", "pray", "fir", "underrepresentation", "genderrelated", "prosecutor", "ballot", "partisan", "tworound", "proceed", "fairly",
           "exofficio", "wake", "par", "request", "observer", "ordinancemake", "reassembly", "dc", "kumar", "nonresident", "articulate", "nomination",

           "reception", "refusal", "materially", "bench", "simplified", "pollutionfree", "examples", "oleum", "leak", "godavarman", "thirumulpad", "taj",
           "mighty", "ambiguity", "loophole", "offender", "cic", "ics", "homosexual", "ab", "designate", "reelection", "bribery", "ramification", "vacancy",
           "enforceable", "nda", "contend", "departmentrelate", "qualified", "nonjudicial", "anomaly", "lgs", "aside", "resorting", "formative",
           "misbehavior", "incapacity", "immunity", "uncodifie", "reconsideration", "thereof", "nonministerial", "tika", "ramji", "chawla", "lacit",
           "clarification", "rhetoric", "superficial", "evm", "auditability", "wrongdoing", "disclose", "reprisal", "reassessment", "robustness", "trail",
           "counting", "turnout", "card", "appointments", "cbfc", "padmaavat", "censorship", "devender", "bhullar", "defendable", "expunge", "litigant",
           "chair", "grantsinaid", "inconsistent", "plane", "decency", "contempt", "defamation", "incitement", "inadequacie", "incentivise", "partys",
           "intraparty", "shreya", "singhal", "cybercrime", "annoyance", "inconvenience", "dismiss", "levy", "evasion", "gsts", "welleducate", "aam",
           "aadmi", "aap", "manager", "assent", "bjps", "upa", "vague", "customary", "fatigue", "row", "liberalize", "issuance", "unwilling", "bandhua",
           "morcha", "paralysis", "investigationcbi", "highprofile", "conducting", "prosecution", "desirability", "unconscious", "quota", "semipresidential",
           "transferable", "proportional", "elector", "proposer", "seconder", "endorsement", "politicized", "proportionality", "caa", "stare", "decisis",
           "unwritten", "compatibility", "incompatibility", "threetier", "wale", "scotland", "ireland", "secondhigh", "disciplinary", "casting", "chairmans",
           "ews", "subcategorization", "statespecific", "squad", "campaigning", "ecis", "reconvene", "promulgation", "ordinancemaking", "subversion",
           "sparingly", "centralisation", "panindian", "divisible", "incentivization", "designing", "cec", "kharak", "sundararajan", "kudankulam",
           "compelling", "narrowly", "brown", "virginia", "abridge", "abrogate", "vidhan", "parishad", "diii", "div", "manohar", "joshi", "nitin",
           "bhaurao", "patil", "nexus", "illconsidere", "purview", "occasionally", "remediation", "ag", "meritbased", "articulation", "unfavorable",
           "unscrupulous", "soul", "implicitly", "civic", "compass", "iii", "iv", "naz", "lgbtq", "presentation", "invalid", "immensely", "understaffed",
           "prolonged", "punish", "reprimand", "countermand", "atal", "bihari", "vajpayeeled", "rejoin", "detach", "centralise", "inspection", "containment",
           "chairmanship", "opaque", "senior", "beholden", "framing", "quasi", "democratically", "faithfully", "aab", "lengthy", "ak", "kr", "lakshmanan",
           "trai", "telecommunication", "cable", "operator", "balancing", "concludesuggeste", "whichever", "governmentowned", "disallowance", "disallow",
           "surcharge", "auditing", "recruit", "tilt", "codify", "unforeseen", "aci", "streamlined", "clarifie", "grading", "samesex", "informational",
           "workload", "exclusively", "convene", "deputy", "absent", "seemingly", "cognizance", "arjun", "gopal", "delhincr", "cpcb", "nongreen", "slot",
           "designation", "environmentallyfriendly", "populism", "populist", "substantive", "wellcrafte", "table", "unauthorized", "malicious",
           "whistleblowing", "unprotected", "wrongdoe", "unfounded", "tamperproof", "resistant", "hack", "manipulate", "repolle", "booth", "voterverified",
           "verify", "print", "polling", "randomly", "raising", "applicability", "propound", "unaccounted", "verifiable", "nris", "constructively", "toll",
           "courts", "advocatesonrecord", "ipc", "occupy", "precensorship", "cinematograph", "certification", "differential", "impressionable", "audiovisual",
           "emotion", "clearance", "misrepresent", "hurt", "denial", "acceptreject", "remit", "languish", "defendability", "doklam", "standoff", "abrogation",
           "canon", "suspension", "dpsp", "comprehend", "creditworthiness", "temporarily", "prerogative", "exempt", "satisfied", "supervisory", "staff",
           "chairperson", "sabhas", "reconsider", "betterinformed", "retire", "staggered", "insulate", "contingent", "understandable", "consistency", "cji",
           "seniormost", "assumption", "opacity", "electioneer", "electioneering", "strategise", "strategizing", "mediation", "staffing", "strategize",
           "ncws", "rao", "researcher", "swift", "unwieldy", "oversized", "narendra", "modis", "interrelated", "defect", "liable", "ravibeas", "protract",
           "vijay", "kelkar", "predecessor", "earmark", "merely", "prorogue", "impeach", "invalidate", "implicit", "harmoniously", "openly", "fearful",
           "unethical", "dinesh", "mpmla", "desam", "tdp", "whip", "tdps", "mps", "diwakar", "reddy", "abstain", "anti", "grossly", "insult", "injury",
           "vaguely", "subjective", "underrepresented", "wellconsidere", "antifarmer", "defend", "militate", "ips", "igst", "destinationbase",
           "destinationbased", "statesunion", "subsume", "excise", "valueadde", "mediumsized", "ninejudge", "unanimously", "intrinsic", "welleducated",
           "transparently", "decentralizing", "bringing", "spontaneity", "anticorruption", "hazare", "lokpal", "efficacious", "cgst", "sgst", "utgst",
           "offenses", "imprisonment", "dismissal", "disloyalty", "subsist", "execution", "stake", "prescribed", "acquit", "writ", "erroneous", "expunging",
           "enlarge", "dilemma", "majoritarianism", "piecemeal", "overhaul", "enforceability", "invent", "expansively", "anr", "potent", "sp", "profitsharing",
           "unlimited", "corrective", "trinamool", "tmc", "janata", "bjp", "coalitionbuilde", "intolerance", "polarize", "ir", "immune", "impinge", "ambiguous",
           "overbroad", "permissible", "downfall", "apprehension", "nagas", "electiondriven", "dilution",
           "hung", "loosely", "intact", "agony", "fate", "irreversible", "rush", "inordinate", "commutation", "justifie", "inversely", "capably"
        ],
        "International Relations": [
           "lanka", "saarc", "bimstec", "indopacific", "indous", "ita", "unesco", "unsc", "indorussian",
           "ecosoc", "maldive", "gujral", "shahbag", "aiib", "aukus", "grouping", "ashgabat", "doha",
           "ndb", "mausam", "mcbride", "auku", "pact", "taliban", "asean", "aagc", "bid", "usiran", "supplier",
           "debt", "nontariff", "ussr", "hardware", "dhaka", "uae", "chabahar", "eu", "idealistic", "postcold",
           "obligation", "crossborder", "isaf", "signatory", "camera", "saudi", "arabia", "unlikely", "wtos", "radicalization",
           "imfs", "distrust", "existential", "bri", "asiapacific", "nontrade", "parallel", "iu", "ipr", "software", "stockholding",
           "jamaateislami", "islamist", "mollah", "protester", "oman", "peacekeeping", "challengesdrawback", "iranian", "utility",

           "intelligenceshare", "rulesbased", "newfound", "havana", "nam", "saarcs", "bric", "traderelate", "djibouti", "indiamaldive",
           "bretton", "wood", "unilateral", "concession", "fraught", "quadrilateral", "erstwhile", "ussoviet", "friend", "friendship",
           "indiaafrica", "cricket", "debttrap", "broadbase", "inflow", "trilateral", "mohame", "maldivian", "swap", "indiasri", "israeli",
           "thai", "philanthropic", "fora", "netzero", "ndcs", "immigration", "immigrant", "multilateralism", "agreedupon", "uri", "islamabad",
           "minus", "adversary", "untapped", "palestine", "indoisrael", "itrelated", "insistence", "distort", "abdul", "quader", "jamaat",
           "bangladeshi", "sectarian", "indiabangladesh", "cpec", "detriment", "powerhouse", "buildup", "thirdlargest", "fastgrowe", "gcc",
           "easing", "leviathan", "mediterranean", "nonalignment", "suitability", "tune", "funder", "covax", "pheic", "messaging", "objectively",
           "timeliness", "upset", "geoeconomic", "supervise", "highend", "nextgeneration", "pios", "ocis", "emirate", "kuwait", "qatar", "forums",
           "idealism", "antiterrorism", "disarmament", "strained", "pakistanin", "nonfunctioning", "realpolitik", "rulesbase", "washington",
           "esteem", "shareholder", "exactly", "westerndominate", "profoundly", "rulebase", "protectionism", "committed", "regionindia",
           "pangong", "demarcate", "encircle", "extraregional", "wb", "middleincome", "programsthe", "countriesthe", "ibrd", "ida", "governing",
           "subscription", "ik", "reciprocal", "informationshare", "smuggling", "relations", "bollywood", "dushanbe", "panasian", "geo", "prism",
           "warexplain", "dub", "competitor", "aksai", "chin", "ussrs", "dissolution", "quantum", "uighur", "outspend", "leading", "sinhalese",
           "scar", "complicated", "embassy", "dutyfree", "ldc", "grantsin", "sourcing", "repayment", "signficant", "exhibition", "aman", "ki",
           "kartarpur", "multiethnic", "separatism", "antiterror", "nonconfrontational", "nontargete", "indiapakistanrussiachina", "matrix",
           "disrespect", "rulebased", "chequebook", "wolf", "disguise", "separatist", "lep", "indiaasean", "fdi", "eas", "aseanled", "arf",
           "indiamyanmarthailand", "kaladan", "multimodal", "transit", "tapi", "appraise", "businessman", "versa", "nonreciprocity", "indiamaldives",
           "relationsand", "ibrahim", "solih", "signing", "rufiyaa", "hicdp", "cochin", "gahdhoo", "ekuverin", "dosti", "ekatha", "mndf",
           "detoxification", "addu", "highimpact", "hanimaadhoo", "gmcp", "nasheed", "pakistanbase", "jihadist", "doom", "prematurely",
           "nairobi", "insist", "unfccc", "nonissue", "firstly", "secondly", "developing", "purchaser", "lankan", "dissimilarity",
           "complementarity", "peoplecentered", "longsustaine", "shoot", "ashghabat", "uzbekistan", "turkmenistan", "accession",
           "ramakien", "javanese", "charity", "jayakumar", "singaporean", "proenvironment", "differentiated", "nonfossil", "fuelbase",
           "solarrich", "transitioning", "burdenshare", "trination", "tri", "patrol", "antichina", "indianamerican", "fundraise", "joe",
           "biden", "referendum", "prepared", "spillover", "countermeasure", "encirclement", "gwadar", "hambantota", "iuindia", "hesitant",
           "modality", "neighbour", "narcotic", "inactive", "indiaadministered", "condemn", "indication", "aftermath", "civilmilitary",
           "dissonance", "stall", "subregional", "bbin", "intra", "interregional", "rim", "al", "qaeda", "haqqani", "tehreeketaliban",
           "ttp", "stabilitya", "supplying", "adversarial", "intc", "americas", "caatsa", "generalized", "gsp", "balancer", "hedging",
           "enemy", "fencing", "uncompetitive", "antiisrael", "admit", "jerusalem", "delegitimize", "jewish", "opponent", "bona", "fide",
           "freeze", "hiring", "bodys", "presently", "indiaisrael", "grown", "dehyphenation", "knowledgeshare", "drip"
        ],
        "Governance": [
          "mdm", "immorality", "sebi", "cadrebase", "pura", "multilevel", "npr", "mfis", "rta", "irda",
          "projectsprogramme", "sblp", "ictbase", "fare", "satyam", "nonstate", "gatishakti", "registration", "container",
          "employable", "blockage", "ulip", "penetration", "cii", "nabard", "avail", "neoliberal", "hybrid", "calorie", "tape",
          "ficci", "nepotism", "favoritism", "pitroda", "urbanrural", "overlapping", "nonnew", "disbursement", "lobbying", "redtapism",
          "talukas", "preparation", "tireless", "crowdfunde", "governmentaide", "vacation", "confederation", "probusiness", "psus", "overhead",
          "subgrante", "broadband", "possibility", "assocham", "mazdoor", "medias", "interdependent", "flagship", "nap", "extraconstitutional",
          "ethic", "intake", "bibek", "debroy", "profitable", "cadre", "workingage", "publication", "editorial", "intersectoral", "resourcesharing",
          "integrated", "domainspecific", "marketoriente", "arbitrage", "fca", "regulator", "rbis", "misconduct", "generic", "generalist", "duplicate",
          "overly", "nfra", "citizenry", "appropriation", "conform", "deviation", "decentralisation", "involved", "ppc", "tnega", "digitalize", "nipah",
          "laud", "lsgs", "prioritization", "watchdog", "crowdsourcing", "governmentcitizen", "smcs", "headon", "chore", "nowadays", "vicechairman",
          "solarpowere", "streetlight", "wifi", "hiwre", "undernourishment", "reportedly", "contaminated", "andolan", "coercion", "stagnant", "neglecting",
          "deregulate", "disinvestment", "nonstrategic", "underperform", "lossmake", "bharatmala", "sagarmala", "ficcis", "technologyict", "iamai", "nso",
          "dhanaadhaarmobile", "specified", "extended", "cancel", "score", "overburdened", "evade", "criminalization", "acceptable", "kinship", "gratitude",
          "unreliable", "underserve", "hacking", "securing", "bodoland", "concede", "leftwe", "crux", "socioeconomicpolitical", "interestbase", "nasscom",
          "aituc", "bms", "issuebase", "chipko", "dravida", "munnetra", "kazhagam", "dmk", "sangathan", "mkss", "consultancy", "tcs", "outrage", "citizenle",
          "threeti", "wellrounded", "tinker", "industryready", "apprentice", "onthejob", "correspond", "revitalization", "schoolage", "revitalize",
          "marginality", "strap", "nonprofitable", "sam", "bag", "accustom", "drawing", "pmkvy", "ehealthcare", "bharatnet", "percent", "mull",
          "contemplate", "monopolization", "monopolize", "huffpost", "bbc", "cnn", "reactive", "vahini", "punitive", "suo", "motu", "unconstitutionality",
          "deworming", "interlinked", "iwmp", "crosssectoral", "resourceshare", "pooling", "interview", "aptitude", "sms", "voicebase", "neo", "pri",
          "combined", "supervision", "episode", "abrupt", "demonetization", "resignation", "urjit", "alok", "verma", "asthana", "questionable", "wrap",
          "compliant", "fume", "pmkisan", "installment", "ajit", "januja", "seniority", "singhania", "servicerelate", "marche", "sitin", "rollback",
          "swaminathan", "waiver", "individually", "appraisal", "lateral", "interdepartmental", "crossfunctional", "yamuna", "expressway", "gati",
          "sensitisation", "prejudice", "misconception", "notorious", "misallocation", "commonwealth", "tarnished", "onesizefitsall", "passport",
          "seva", "kendras", "timebound", "measurable", "environmentalist", "demerit", "redundancy", "digit", "uidai", "proof", "usual", "subdistrict",
          "acceptability", "assessed", "pragmatic", "jeevika", "lift", "communityled", "enron", "ramalinga", "raju", "confess", "falsify", "cadrebased",
          "tapism", "polio", "viz", "adhar", "gover", "nance", "genderspecific", "bureaucratization", "chamber", "nasscoms", "devolving", "overfamiliarity",
          "tighten", "suspect", "relatedparty", "remuneration", "depositor", "fraudulent", "wrongful", "ombudsman", "lokayuktas", "lokayukta", "malfeasance",
          "immoral", "bihars", "fodder", "embezzlement", "bribe", "vyapam", "grassrootslevel", "systematically", "overindebtedness", "slew", "borrower",
          "malegam", "sks", "darling", "lending", "recordkeeping", "eshakti", "bookkeeping", "groupsshgs", "selfconfidence", "communitydriven",
          "swarnajayanti", "swarozgar", "sgsy",
          "buyerseller", "synergistic", "statele", "slowmoving", "muchdebate",
          "manageability", "homogeneity", "mineralrich"
        ],
        "Social Justice": [
        "nhrc", "shgs", "microfinance", "dbt", "alleviation", "disability", "donor", "reward", "pds", "mdg", "athlete", "preventive",

        "restructuring", "geriatric", "rpwd", "mdgs", "rte", "divergence", "css", "wastage", "review", "malaria", "anticipate", "clinic",
        "policys", "communitylevel", "mpi", "sponsor", "leakage", "olympic", "icd", "publicprivate", "ppps", "recommendation", "compulsory",
        "nonfood", "reporting", "awa", "centrally", "statesponsore", "hivaid", "millennium", "immunization", "telemedicine", "successive",
        "enrollment", "meal", "spending", "squeeze", "microfinancing", "conformity", "attendance", "ranking", "participatory", "noncompliance",
        "redressal", "intermediary", "targeted", "janani", "suraksha", "jsy", "synchronization", "professor", "rights", "investigate", "midday",
        "secondary", "tertiary", "ncp", "pocso", "independently", "costeffectiveness", "gendersensitive", "microcredit", "decisionmaking",
        "networking", "kudumbashree", "jan", "capacitybuilde", "lifelong", "mohalla", "incomebase", "admission", "antenatal",
        "penal", "welldesigne", "update", "revise", "ameliorate", "targeting", "collateral", "deter", "selfemployment", "subsidized",
        "statesponsored", "khelo", "sporting", "besides", "deft", "macroeconomic", "bottleneck", "rbi", "aids", "nacp", "vector", "borne",
        "nvbdcp", "healthrelate", "uip", "nhm", "nrhm", "corresponding", "synchronize", "toilet", "anticipated", "middleman", "showpiece",
        "investigation", "advisory", "krishi", "incentivebased", "dise", "read", "tns", "diagnostic", "accredit", "standalone", "stunt",
        "sensitization", "doctor", "session", "womens", "multipli", "pmjdy", "twin", "mahalir", "thittam", "microenterprise", "shg",
        "prerequisite", "keralas", "impressive", "subcenter", "amma", "socioeconomically", "wellstructured", "vocation", "baby", "kit",
        "newborn", "ujjwala", "entitlement", "bandhan", "previous", "comptroller", "auditor", "cag", "fcra", "cse", "wwfindia", "vanashakti",
        "disaggregate", "iitsiim", "modecriteria", "accountable", "stipulate", "binding", "punishment", "seriousness", "municipal",
        "timeframe", "unaware", "noninclusive", "legally", "revision", "audits", "policymaking", "prioritie", "panacea", "recipient",
        "pmmy", "deendayal", "antyodaya", "yojananational", "daynulm", "triumph", "glory", "victor", "shower", "hint", "athletic",
        "talented", "spot", "elaborating", "purchase", "prudent", "wellfunctione", "slowdown", "statistical", "summit", "hivaids",
        "package", "checkup", "referral", "preschool", "immunize", "seven", "vaccinepreventable", "uns", "underfive", "nuhm", "mmr",
        "dengue", "halt", "hiv", "optimism", "hygienerelated", "behavioral", "adjustment", "synchronizing", "steadfast", "upgrading",
        "periodic", "communitys", "prison", "custodial", "nhrcs", "passing", "hearing", "sinchayee", "fasal", "bima", "pmfby", "unless",
        "swedish", "functional", "incentivebase", "akshaya", "patra", "deregistere", "duplication", "greenpeace", "suspend", "license",
        "allege", "inextricably", "welldesigned", "homebase", "dementia", "homebased", "operational", "underserved", "outofpocket",
        "budgetary", "evidencebase", "offence", "nfh", "imr", "umr", "underweight", "subpar", "uncrpd", "ratify", "nondiscrimination",
        "reasonable", "guardians", "realization", "helping", "onthe", "elusiveness", "highincome", "underdevelopment", "attainment",
        "masculinity", "genderequitable", "heforshe", "bell", "bajao", "breakthrough", "advertising", "antiharassment", "grassroot",
        "selfemploye", "reinvest", "grameen", "humongous", "concurrently", "poultry", "selfesteem", "keeping", "mann", "deshi", "sahakari",
        "shgbank", "remarkably", "reorient", "revamp", "abhiyans", "chalo", "chalein", "incomplete", "aforementioned", "tn", "ensuring",
        "operationalization", "ecce", "technologydriven", "tangible", "chart", "hdi", "sme", "inclined", "donordriven", "navigate", "stubbornly",
        "weight", "disproportionately", "nutritious", "unintende", "gramin", "pmayg", "ruralcentric", "noteworthy", "consultation", "nadus",
        "wellregarde", "tnhsp", "distract", "pregnant", "sadak", "pmgsy", "communitybased", "pmuy", "scsp", "tsp", "intention", "edible",
        "uptake", "underutilization", "shortcoming", "irregularity", "csos", "grassrootsbase", "goonj", "barefoot", "pratham", "oftenneglecte",
        "smile", "industryacademia", "uptodate", "everchanging", "semiurban", "bandhans", "customize", "detection", "phcs", "chc", "vhsc",
        "communityle", "clt", "defecation", "exact", "examination", "rangarajan", "underestimate", "costofliving", "regionspecific", "paeg",
        "deserve", "kerosene", "ifpri", "outstrip", "sanctioned", "completion", "backing", "datadriven", "tightening", "accuse", "subgroup",
        "nuanced", "pressing", "antipoverty", "probable", "dedication", "medalist", "morale", "overemphasis", "institutes", "distinguished",
        "esteemed", "aiml", "siphon", "divert", "error", "ineligible", "eligible", "aadhaarlinke", "illiteracy", "nonetheless", "healthdiscuss",
        "worry", "playing", "complain", "rashtriya", "rkvy", "complication", "commendable", "incomebased", "qs", "enhancement", "campus",
        "substandard", "ger", "udise", "records", "bureau", "unreported", "sansad", "outcomes", "lobby", "groundlevel"
        ],
        "Economy": [
            "ifs", "supermarket", "ricewheat", "frbm", "microirrigation", "labourintensive", "milk", "ration", "favourable", "paddy", "seasonality",
            "fertiliser", "irrigate", "nutp", "ddt", "nwp", "assurance", "realise", "larr", "informalization", "intragenerational", "economys", "changer",
            "distortion", "lcgt", "vshape", "horticultural", "nonfarm", "mega", "hyv", "agroclimatic", "unviable", "sez", "upstream", "mandi", "calculation",
            "careless", "leasing", "mous", "monoculture", "fpos", "variable", "pointer", "costly", "labourer", "determinant", "fpi", "weed", "seller",
            "aggregation", "shanta", "fibre", "premature", "redevelopment", "restrictive", "notify", "pli", "pahal", "fpis", "perishability", "utilisation",
            "assured", "resettlement", "rupee", "baba", "kalyani", "sprinkler", "unorganised", "spoilage", "rfid", "rollout", "lender", "estimation", "subsidise", "cgt", "informalisation",
            "globalisation", "deduction", "gestation", "npas", "distributive", "persuasive", "landlordism", "bumper", "sm", "dormant", "pem", "pwlm", "branding", "cropdiversification", "eodb",
            "igp", "welldraine", "seasonally", "unproductive", "apmcs", "intermediation", "commercially", "phenomenal", "overdependence", "siksha",
            "stabilise", "airway", "unskille", "finished", "lowcapacity", "archaic", "sia", "multistage", "distorted", "cad", "soybean", "sectorwise",
            "constructing", "eco", "agrimarkete", "jnnurm", "brt", "pedestrian", "npa", "yearround", "percapita", "waterstresse", "percolation",

            "localise", "hoarding", "cess", "asymmetry", "retailer", "eway", "transactional", "jandhan", "basically", "unbanked", "clutch", "guzzle",
            "agrimarket", "tpds", "computerization", "productively", "idh", "nip", "rightsbase", "manifold", "formalization", "outsource", "arrive", "gec",
            "bajra", "kodo", "glutenfree", "nk", "hra", "client", "kyc", "lend", "uncultivable", "sectoral", "default", "statemarket", "agriculturefriendly",
            "benami", "exponentially", "bpo", "rabi", "kharif", "optional", "unutilized", "exportoriente", "neeranchal", "rating", "joblessness", "flaunt",
            "privatisation", "fdis", "firewood", "mnc", "moneylender", "undernourished", "rear", "bottomup", "shortsightedness", "laissezfaire", "oligopoly",
            "counterrevolutionary", "alienation", "gini", "coefficient", "attendant", "selfcorrecting", "lightly", "freezing", "sampling", "nonfarme",
            "irradiation", "laggedbehind", "grossdomestic", "postreform", "industrialpolicy", "lof", "confusing", "somehow", "wrong", "inputintensive",
            "reinvent", "pmformalization", "pmfme", "dipp", "autocomponent", "scaledup", "surely", "comb", "gmr", "gvk", "adani", "nonaero", "aai",
            "noninsurable", "concessional", "veterinary", "focusse", "fisherie", "mesh", "scalable", "correction", "gauge", "webbase", "visione",
            "simplerfaster", "ghost", "paternal",
            "pt", "deen", "dayal", "upadhyaya", "kaushalya", "ddugky", "ssa", "wheatrice", "vigorously", "cultivable", "subsequently"
        ],
        "Science and Technology": [
         "nanotechnology", "antibiotic", "signature", "jwst", "fdcs", "printing", "composite", "robot", "drs", "led", "boseeinstein",
         "opensource", "hosting", "inhouse", "invention", "copyright", "breeder", "hubble", "therapeutic", "biopharma", "gaganyaan", "biotech",
         "infectious", "telescope", "sciencebase", "biotechnological", "umpire", "bat", "plutonium", "crew", "biosimilar", "pathogen", "implant",
         "visvesvaraya", "consumeroriente", "novartis", "prize", "fbrs", "covaxin", "microgravity", "patenting", "exoplanet", "biofertilizer",
         "biopesticide", "wound", "radar", "nano", "lifespan", "galaxy", "boson", "prof", "satyendra", "nath", "visvesvarayas", "dose", "fdc",
         "glivec", "iprs", "fbr", "threestage", "gene", "biocon", "isotope", "memory", "serum", "misappropriation", "webb", "analogy", "impoverished",
         "bhabha", "pokhran", "versatility", "diseaseresistant", "nanoscience", "thalassemia", "cure", "antimicrobial", "sps", "gainful", "biopiracy",
         "inappropriate", "drugresistant", "evergreene", "signer", "slice", "onfield", "ball", "machinebase", "akasaki", "amano", "nakamura", "inventor",
         "lighting", "bulb", "fissile", "prototype", "mars", "abort", "isros", "somewhat", "covovax", "covishield", "viral", "harmless", "triumf",
         "infrared", "detective", "mystery", "humanitys", "interwoven", "tuberculosis", "inexpensive", "atom", "homi", "patriot", "ballistic", "fungal",
         "nanometer", "nanotech", "december", "celestial", "leukemia", "cornea", "transplant", "biomaterial", "pathbreake", "nonproliferation",
         "harnessing", "mitra", "sagara", "nanomaterial", "underpin", "superconductivity", "condensate", "bec", "pps", "constellation", "bandicoot",
         "genrobotic", "becoming", "attraction", "laboratory", "dosage", "medication", "incorrect", "selfmedication", "authenticate", "nonrepudiation",
         "slicing", "printer", "customization", "prosthetic", "paramount", "reallife", "evergreening", "skyrocket", "fool", "lbw", "ultraedge", "thirdparty",
         "highperformance", "positional", "locational", "costefficiency", "isamu", "hiroshi", "shuji", "diode", "ujala", "laptop", "saksharta", "ledscreen",
         "phototherapy", "neonatal", "jaundice", "drev", "nonfissile", "pu", "pfbr", "kalpakkam", "actinides", "radiotoxicity", "unwavere", "ingenuity",
         "subheading", "mom", "perilous", "involves", "threemember", "zolgensma", "spinal", "muscular", "atrophy", "biologic", "trastuzumab", "breast",

         "profile", "oncology", "exciting", "knpp", "commence", "operationalize", "react", "biotechs", "inactivated", "dummy", "subunit", "tattoo",
         "coronaviruss", "vyomanaut", "lifesupport", "prestige", "spacex", "redefine", "chick", "hatch", "piecing", "peel", "immunology", "weakened",
         "measle", "mump", "rubella", "wanted", "poster", "apprehend", "droughttolerant", "unimagine", "unparalleled", "viruss", "transforming", "insulin",
         "molbios", "truenat", "salinetolerant", "bio", "cleanup", "rhizobium", "leguminous", "biofortification", "biodigester", "riverine", "carp",
         "heavylift", "orbital", "inspace", "unyielde", "aec", "trombay", "aeet", "barc", "tarapur", "embargo", "pressurize", "phwr", "phwrs", "undergoes",
         "fission", "neutron", "reprocess", "batch", "wipo", "replete", "cognizant", "compendium", "spanish", "sesderma", "sls", "woundheale", "nonnovel",
         "usbased", "novelty", "inventive", "wipos", "chickpea", "lever", "outpace", "americanmade", "verylongrange", "unmatched", "stealth", "cruise",
         "triumfs", "fallout", "bacillus", "thuringiensis", "bollworm", "saltol", "nutrientenriche", "stewardship", "reemphasize", "nanoscale",
         "microchip", "nanotechnologys", "resourceefficient", "mangalyaan", "martian", "gagan", "terrestrial", "insat", "gsat", "broadcasting",
         "prerecord", "modelling", "infrare", "observatory", "servicing", "observational", "reionization", "spectra", "surpasse", "capsule",
         "cosmoss", "diseased", "dysfunctional", "injure", "regeneration", "waiting", "defective", "neurological", "neurodegenerative", "parkinson",

         "alzheimer", "neuron", "tumor", "controlledenvironment", "triton", "foodwork", "hydroponic", "molecular", "herald", "photon", "gluon",
         "solidstate", "upswe", "upswing", "ascribe", "birac", "ignition", "aerb", "chernobyl", "fukushima", "kakrapar", "longlived", "radioactive",
         "nonsignatory", "npt", "nonparticipant", "satiate", "leukaemia", "tracing", "tracetogether", "teladoc", "byju", "disinfection", "triale",
         "sanitization", "screening", "cowin", "scheduling", "mvisvesvaraya", "anicut", "highyielding", "swarna", "preparatory", "restate", "symbolise",
         "reentry", "bengalurubase", "achira", "labs", "microfluidicsbased", "labonachip", "lowcost", "cdri", "amphotericin", "azar", "toxicity",
         "nanoparticle", "gujaratbase", "amrutam", "nanosilver", "coat", "bandage", "algelimdg", "adjuvant", "nanosized", "gel", "droplet",
         "biocompatible", "sree", "chitra", "tirunal", "nanostructure", "titanium", "orthopedic", "pervasiveness", "albert", "einstein",
         "amplification", "condensation", "electron", "condense", "eric", "cornell", "carl", "wieman", "wolfgang", "ketterle", "rubidium",
         "nanobot", "chemotherapy", "purification", "nanotechbase", "filter", "nanofertilizer", "nanopesticide", "nanosensor", "nanoelectronic",
         "vicinity", "manhole", "maruti", "suzuki", "invento", "tartansense", "farmrobotic", "dst", "nidhi", "nit", "eyantra", "siddha", "revocation",
         "neem", "timeteste", "resourcepoor", "openness", "dull", "pure", "moocs", "ather", "applicationoriente", "attractiveness", "trivial",
         "pharma", "gilead", "sofosbuvir", "hepatitis", "tb", "pharmacist", "prescribing", "napamr", "paucity", "pharmacy", "indiscriminately",
         "termscopyright", "vigilant", "giver", "cryptographic", "handwritten", "email", "sender", "threedimensional", "computeraide", "successively",
         "stepbystep", "epoxy", "polyester", "nylon", "fibrous", "unidirectional", "bidirectional", "layup", "sprayup", "pultrusion", "filament",
         "winding", "injection", "moulding", "harden", "addressal", "painkiller", "muscle", "relaxant", "gastric", "dizziness", "dosing",
         "hypertension", "summarizing", "udr", "technologybase", "hawkeye", "balltracke", "snickometer", "soundbase", "muffle", "faint", "ashe",
         "australias", "steve", "smith", "englandindia", "icc", "confidential", "innovator", "reproduce", "reproduction", "nonobvious", "csir",
         "curcumin", "thwart", "ascertainable", "secrecy", "cocacola", "clouds", "minimal", "risky", "solarwind", "swiss", "pivot", "riskbenefit",
         "promising",
        "formatted", "downside", "strengthtoweight", "boeing", "dreamliner", "carbonfibre", "aerospace", "nal", "reconnaissance", "servers"
        ],
        "Environment and Ecology": [
           "ncap", "linking", "photochemical", "cdms", "nmcg", "kyoto", "gothenburg", "nanami", "osowog", "pithead", "nogo", "ghgs", "aqgs",
           "ozone", "cdm", "mercury", "turbidity", "discard", "bioremediation", "iczm", "postfacto", "submission", "dolphin", "erratic", "snow",
           "glasgow", "grassland", "aqg", "microgram", "effluent", "vocs", "voc", "ji", "iris", "salinewater", "nesting", "renovation", "citylevel",
           "cleaning", "width", "armor", "seawall", "breakwater", "dissipate", "surges", "relocation", "commencement", "regularize", "megapode",
           "woodpecker", "islands", "desertadapted", "fox", "benefitshare", "damanganga", "pinjal", "hydropow", "godavarikrishna", "industrie",
           "airshe", "connetion", "minigrid", "offgrid", "interconnected", "modi", "ecoconscious", "enthusiast", "pristine", "megadiverse", "poppy",
           "leopard", "hemis", "rhododendron", "panda", "singalila", "namdapha", "sarus", "skimmer", "liontailed", "macaque", "nilgiri", "tahr", "silent",
           "cycas", "beddomei", "pangolin", "simlipal", "kambalakonda", "whohow", "sulphur", "airshedbased", "irrawaddy", "blackbuck", "formerly", "bharatpur",
           "activitieseg", "jalyukt", "shivar", "watersave", "waterefficient", "kandi", "bundelkhand", "peroxyacetyl", "nitrate", "pan", "hydrocarbon", "compress",
           "cng", "cycling", "pedestrianfriendly", "facto", "watersaving", "ammonia", "nh", "dredging", "obstruct", "erosionlike", "seagrass", "ch", "nitrous", "hydrofluorocarbon",
           "hfcs", "perfluorocarbon", "pfcs", "hexafluoride", "sf", "countrie", "baseline", "erus", "conversation", "likeminded", "lmdc", "sidn", "sidns", "emissions", "regionseg",
           "gaja", "thoroughly", "coalfired", "arsenic", "khurja", "authorization", "limestone", "incremental", "gangathe", "namami", "sonbhadra", "amenitieseg", "moef", "indiatake", "multiface",
           "gaon", "periyasamypuram", "driedup", "palm", "olive", "ridley", "dieoff", "sandbank", "hefty", "inaction", "periyasamy", "puram", "renewal", "detract", "reevaluate", "decay", "reuse",
           "cityspecific", "nonattainment", "excavation", "residual",
           "conservationcite", "marsh", "swamp", "bog", "establishe", "ambient", "kollam", "alappuzha", "pathanamthitta", "kottayam", "ernakulam"
             ],

             "Internal Security" : [
              "lwe", "ogws", "airspace", "mob", "launder", "afspa", "cyberspace", "radicalism", "transborder", "outer", "indiamyanmar",
        "chinapakistan", "nonimplementation", "certin", "surrender", "localization", "triangle", "loc", "sns", "fence", "seizure",
        "samadhan", "lweaffecte", "indianepal", "preempt", "radicalize", "srikrishna", "ulfa", "highresolution", "nscnk", "naxalbari",
        "unodc", "indoctrination", "nrc", "cibms", "subversive", "sre", "iap", "reintegrate", "dark", "syria", "bn", "longitudinal",
        "patrolling", "thangjam", "manorama", "malware", "indiachina", "badp", "forensic", "organisational", "detention", "nscn", "klf",
        "nciipc", "militancy", "scourge", "isiss", "profiteering", "defunct", "laos", "counterinsurgency", "imager", "jamaate", "overground",
        "sponsorship", "counterpropaganda", "preemptively", "swachhta", "kendra", "budap", "malkangiri", "chaos", "lynch", "alwar", "maoist",
        "racket", "aml", "someone", "haja", "warrant", "marking", "gilgitbaltistan", "karot", "bust", "lethal", "interagency", "opiumproduce",
        "intersect", "botnet", "underreporte", "psychotropic", "verifie", "encryption", "counternarrative", "pla", "mnrf", "manipurbase",
        "partake", "icp", "moreh", "ifcior", "rukmini", "gsata", "malfunction", "cyberterrorism", "dissenter", "bhima", "koregaon", "emanating",
        "yaba", "tablet", "nscnim", "kuki", "phishing", "naxalaffected", "discontentment", "prahaar", "darshan", "crpfs", "kashmiri", "shopian",
        "jangal", "jameen", "oxford", "ascertain", "infest", "associated", "neighbouring", "statehood", "endurance", "cocaine", "methamphetamine",
        "militarygrade", "conceal", "burglary", "resale", "gang", "boko", "haram", "trafficker", "samriddhi", "sandesh", "telanganas", "gurukul",
        "pesa", "greyhound", "fueling", "karakoram", "scheduled", "reportage", "infiltrate", "eelam", "ltte", "hotbed", "unchecked", "sporadic",
        "tense", "alertness", "servitude", "indotibetan", "itbp", "transgression", "banning", "jamaateislamic", "abet", "insurgencyprone",
        "attainable", "paradoxical", "alqaeda", "panchkula", "everywhere", "profitmake", "selffinance", "intergroup", "fundraising", "guise",
        "intelligencebased", "insurgencyaffecte", "intelligenceled", "arsenal", "directorgeneral", "inspector", "interservice", "isi", "natgrid",
        "collate", "collaborating", "obnoxious", "intertwine", "astute", "dashboardbase", "kpis", "kras", "theatre", "halve", "modernisation",
        "underdeveloped", "combatant", "cardinal", "subset", "baiga", "sterilization", "insensitivity", "disempowerment", "chotanagpur", "pargana",
        "intrinsically", "electronics", "foci", "answr", "governmentle", "dadri", "stoke", "suspicion", "fatal", "lynching", "baseless", "decisively",
        "strategie", "cannabis", "mizorambangladesh", "interception", "consignment", "destine", "poignant", "illegallygained", "indiaspecific", "infer",
        "chase", "retaliate", "junk", "militarization", "mosaic", "doubleedge", "fissure", "counteraction", "afghanistanpakistan", "afpak",
        "counterradicalism", "cbse", "analyst", "battlefield", "nationstate", "intending", "reported", "blackout", "cyberespionage", "hangover",
        "insidious", "uss", "fbi", "extradition", "chakravyuh", "obscure", "globalize", "wirecard", "hide", "revelation", "trick", "deceptive",
        "dupe", "stalk", "harass", "isil", "daesh", "iraqi", "caliphate", "ultra", "conservative", "unislamic", "areeb", "majeed", "disenfranchised",
        "fakkurudeen", "usman", "deradicalization", "pioneering", "contravention", "fiduciary", "refuge", "antipiracy", "redefinition", "eez",
        "seychelle", "hormuz", "adversarys", "sahiwal", "lahorekarachi", "motorway", "upsetting", "rashakai", "dhabeji", "optic", "bureaus",
        "ncrb", "liaise", "downward", "fiuind", "traceability", "gobal", "internation", "fatfs", "transparen", "cy", "capabilitie", "transformati",
        "draconian", "disturbed", "extrajudicial", "afspas", "torture", "reevaluation", "lawless", "perpetual", "palk", "creek",
        "marshy", "katchatheevu", "amphan", "wariness", "balochistan", "wary", "opiumgrowe", "gunrunne", "sandwich", "cyberbullying", "nortonlifelock",
        "bully", "impersonate"
        ],

        "Disaster Management": [
         "disaster", "risk", "management", "earthquake", "impact", "preparedness", "india", "system", "vulnerability", "cloudburst"

        ],
        "Ethics": [
            "substantiation", "prospective", "quotation", "contextual", "nonpartisanship",
            "misutilization", "rationality", "fortitude", "sin", "apj", "greed", "undesirable",
            "nonperformance", "rawl", "forgive", "afraid", "mindfulness", "ei", "lama", "amte", "kiran",
            "bedi", "osa", "bravery", "abraham", "setback", "dalai", "shoe", "guilt", "teresa", "listen", "mistake",
            "cvc", "breathing", "recuse", "asylum", "rohingya", "syrian", "technoeconomic", "socioethical", "kautilyas",
            "innovativeness", "cricketer", "cnp", "whistle", "lincolns", "prakash", "periphery", "rwandan", "shame",
            "corruptionfree", "cellscommission", "weber", "subtopic", "selfrealization", "happy", "tame", "impulse", "conflicting",
            "sreedharan", "nroer", "netf", "parakh", "niecce", "nacbank", "infosys", "victimization", "blower", "lincoln", "coolingoff",
            "lbsnaa", "gift", "refrain", "truthful", "temper", "bezwada", "wilson", "youthled", "preoccupation", "travesty", "footstep",
            "kailash", "satyarthi", "ratan", "expressly", "poison", "falsehood", "persevere", "edhi", "cheat", "eternal", "verbal", "icj",
            "rawlss", "ignorance", "clothe", "dictator", "pleasure", "conflictofinter", "aristotle", "emotionally", "professionally", "civilized",
            "eprocurement", "unexamined", "impermanence", "rohini", "sindhuri", "dasari", "gangrape", "composure", "nagpal", "julio", "ribeiro", "wisely",
            "textbook", "muchneede", "mis", "temptation", "entrance", "constitutionalism", "wholly", "preponderance", "motivated", "hopeful", "metoo",
            "vivekanand", "advisor", "nun", "righteousness", "seshan", "humility", "cruciality", "negativeminde", "expected", "erik", "erikson",
            "rohingyas", "demonstrating", "mandakini", "intersection", "reckon", "dmrc", "maheshwari", "minded", "shetty", "stewart", "inspiring",
            "chanu", "endeavor", "thomas", "deed", "ipl", "assignment", "taste", "tongue", "bit", "warren", "holocaust", "breivik", "feud", "cleansing",
            "israelpalestine", "russiaukraine", "innovatively", "creatively", "apartheid", "aamir", "sattar", "arunachalam", "muruganantham", "selfinter",
            "subordination", "meanwhile", "countryman", "anniversary", "query", "hul", "passion", "bonaparte", "heated", "counselor", "unconsciously",
            "dependable", "veil", "birthday", "ataturk", "worldview", "contentment", "awarenessraise", "exemplified", "sainath", "revenge", "iyer",
            "nonhuman", "elicit", "rage", "heed", "knowledgeable",
            "tom", "dreadful", "illustrationdure", "syphilis", "yes", "sure", "beneficence", "etendere", "mygovin"
            ]

        }

    # Check which category the text belongs to
    for category, keywords in categories.items():
        if any(keyword in text.lower() for keyword in keywords):
            return category

    return "Other"


# Apply the labeling function to each processed text
labels = [label_document(text) for text in processed_texts.values()]

# Create a DataFrame with the labeled data
import pandas as pd
df = pd.DataFrame({'filename': list(processed_texts.keys()), 'text': list(processed_texts.values()), 'label': labels})

# Check the first few rows of the labeled data
print(df.head(5))

"""# Tokenization"""

from transformers import DistilBertTokenizer

# Load DistilBERT tokenizer
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

# Tokenize the training and validation texts
train_texts = df['text'][:int(0.8*len(df))].tolist()  # 80% for training
val_texts = df['text'][int(0.8*len(df)):].tolist()  # 20% for validation

train_encodings = tokenizer(train_texts, padding=True, truncation=True, max_length=512)
val_encodings = tokenizer(val_texts, padding=True, truncation=True, max_length=512)

"""# HUGGING FACE TOKEN"""

from huggingface_hub import notebook_login

"""# Create PyTorch Dataset"""

import torch

class TextDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

    def __len__(self):
        return len(self.labels)

# Convert labels to numerical values (for model training)
label_mapping = {label: idx for idx, label in enumerate(df['label'].unique())}
train_labels = [label_mapping[label] for label in df['label'][:int(0.8*len(df))].tolist()]
val_labels = [label_mapping[label] for label in df['label'][int(0.8*len(df)):].tolist()]

# Create PyTorch datasets
train_dataset = TextDataset(train_encodings, train_labels)
val_dataset = TextDataset(val_encodings, val_labels)

"""# Train the model"""

import torch
from transformers import DistilBertForSequenceClassification, AdamW
from torch.utils.data import DataLoader

# Check if GPU is available, otherwise use CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load the model for sequence classification
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=len(label_mapping))

# Move the model to the appropriate device (GPU or CPU)
model.to(device)

# Set up optimizer
optimizer = AdamW(model.parameters(), lr=5e-5)

# Create DataLoader for training and validation
train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=4, shuffle=False)

# Training loop
epochs = 3
for epoch in range(epochs):
    model.train()
    total_train_loss = 0

    for batch in train_loader:
        optimizer.zero_grad()  # Zero gradients

        # Move batch to the same device as the model (GPU or CPU)
        batch = {key: value.to(device) for key, value in batch.items()}

        # Forward pass
        outputs = model(**batch)
        loss = outputs.loss
        total_train_loss += loss.item()

        # Backward pass
        loss.backward()
        optimizer.step()

    avg_train_loss = total_train_loss / len(train_loader)
    print(f"Epoch {epoch+1}, Training Loss: {avg_train_loss}")

"""# Validation and classification report"""

# Validation Loop
model.eval()
val_preds = []
val_true = []

with torch.no_grad():
    for batch in val_loader:
        batch = {key: value.to(device) for key, value in batch.items()}
        outputs = model(**batch)
        logits = outputs.logits
        preds = torch.argmax(logits, dim=-1)
        val_preds.extend(preds.cpu().numpy())
        val_true.extend(batch['labels'].cpu().numpy())

# Filter target names for present classes
unique_classes = sorted(set(val_true))
filtered_target_names = [list(label_mapping.keys())[cls] for cls in unique_classes]

# Metrics
accuracy = accuracy_score(val_true, val_preds)
print(f"Validation Accuracy: {accuracy}")
print(classification_report(val_true, val_preds, target_names=filtered_target_names))

import matplotlib.pyplot as plt
import numpy as np

# Labels and metrics from the report
labels = [
    "Polity and Constitution", "Governance", "Economy", "Social Justice",
    "Post-Independence India", "Geography", "Modern History", "Art & Culture",
    "World History", "Indian Society", "Other", "Science and Technology",
    "International Relations", "Ethics", "Internal Security"
]

precision = [1.00, 0.70, 0.67, 0.00, 0.73, 0.78, 0.59, 0.86, 0.00, 0.00, 0.33, 0.75, 0.00, 0.00, 0.36]
recall = [0.28, 0.90, 0.33, 0.00, 0.87, 0.64, 0.10, 0.40, 0.00, 0.00, 0.62, 0.60, 0.00, 0.00, 0.80]
f1_score = [0.44, 0.78, 0.44, 0.00, 0.79, 0.70, 0.74, 0.55, 0.00, 0.00, 0.43, 0.67, 0.00, 0.00, 0.50]

x = np.arange(len(labels))  # Label locations
width = 0.25  # Bar width

# Create subplots
fig, ax = plt.subplots(figsize=(15, 8))

# Plot bars
bar1 = ax.bar(x - width, precision, width, label='Precision', color='b')
bar2 = ax.bar(x, recall, width, label='Recall', color='g')
bar3 = ax.bar(x + width, f1_score, width, label='F1-Score', color='r')

# Add labels, title, and custom x-axis tick labels
ax.set_xlabel('Topics')
ax.set_ylabel('Metrics')
ax.set_title('Classification Metrics by Topic')
ax.set_xticks(x)
ax.set_xticklabels(labels, rotation=45, ha="right")
ax.legend()

# Annotate bars with their values
def add_values(bars):
    for bar in bars:
        height = bar.get_height()
        if height > 0:
            ax.text(bar.get_x() + bar.get_width()/2., height, f'{height:.2f}', ha='center', va='bottom')

add_values(bar1)
add_values(bar2)
add_values(bar3)

# Tight layout for better spacing
plt.tight_layout()

# Save or show plot
plt.savefig("classification_metrics.png", dpi=300)  # Save as high-res image for research paper
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Labels and accuracy values from the report
labels = [
    "Polity and Constitution", "Governance", "Economy", "Social Justice",
    "Post-Independence India", "Geography", "Modern History", "Art & Culture",
    "World History", "Indian Society", "Other", "Science and Technology",
    "International Relations", "Ethics", "Internal Security", "Overall"
]

accuracy = [
    0.28, 0.90, 0.33, 0.00, 0.87, 0.64, 0.10, 0.40, 0.00, 0.00,
    0.62, 0.60, 0.00, 0.00, 0.80, 0.66  # Overall accuracy added at the end
]

# Create bar plot
fig, ax = plt.subplots(figsize=(12, 6))

bars = ax.bar(labels, accuracy, color='skyblue', alpha=0.8)

# Add labels and title
ax.set_xlabel('Topics')
ax.set_ylabel('Accuracy')
ax.set_title('Accuracy by Topic')
ax.set_xticklabels(labels, rotation=45, ha='right')

# Annotate bars with accuracy values
for bar in bars:
    height = bar.get_height()
    if height > 0:  # Only annotate non-zero bars
        ax.text(bar.get_x() + bar.get_width()/2., height, f'{height:.2f}', ha='center', va='bottom')

# Adjust layout
plt.tight_layout()

# Save or show the plot
plt.savefig("accuracy_by_topic.png", dpi=300)  # Save as high-res image
plt.show()

import matplotlib.pyplot as plt

# Overall accuracy values (include variations if available)
epochs = [1, 2, 3, 4, 5]  # Example epochs or training rounds
accuracy_values = [0.60, 0.62, 0.63, 0.65, 0.6553]  # Accuracy progression

# Plot the line graph
plt.figure(figsize=(8, 5))
plt.plot(epochs, accuracy_values, marker='o', color='blue', linestyle='-', linewidth=2)

# Add labels and title
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.title('Overall Accuracy Progression')
plt.xticks(epochs)  # Ensure all epochs are shown
plt.ylim(0.5, 0.7)  # Adjust y-axis limits for better visualization

# Annotate points with accuracy values
for i, acc in enumerate(accuracy_values):
    plt.text(epochs[i], acc, f'{acc:.2f}', ha='center', va='bottom')

# Add grid for better readability
plt.grid(True, linestyle='--', alpha=0.6)

# Save or show the plot
plt.savefig("overall_accuracy_line_graph.png", dpi=300)  # Save as high-res image
plt.show()

"""# Prediction Distributions"""

from collections import Counter
print("Validation Predictions Distribution:", Counter(val_preds))

"""## Prediction with sample text"""

print("Unique classes in val_true:", set(val_true))
print("Unique classes in val_preds:", set(val_preds))
print("Classes in label_mapping:", list(label_mapping.keys()))

# Example of predicting the label for a new document
new_text = "The rise in agricultural exports,post the Independence."
new_encodings = tokenizer([new_text], padding=True, truncation=True, max_length=512)
input_ids = torch.tensor(new_encodings['input_ids']).to(device)
attention_mask = torch.tensor(new_encodings['attention_mask']).to(device)

# Get predictions
model.eval()
with torch.no_grad():
    logits = model(input_ids=input_ids, attention_mask=attention_mask).logits

# Get predicted class (topic)
predicted_class = torch.argmax(logits, dim=-1).item()
print(f"The predicted class for the document is: {predicted_class}")
# Map the predicted class index to its label
predicted_label = class_to_label[predicted_class]

# Print the result

print(f"The predicted label for the document is: {predicted_label}")

"""# Save Model"""

model.save_pretrained('/content/drive/MyDrive/distilbert_model')
tokenizer.save_pretrained('/content/drive/MyDrive/distilbert_model')
print("Model and tokenizer saved successfully.")

"""# End"""